// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB4L7YtiE8HJM8TPF7Ja1SgQe1teKygvA',
    appId: '1:696348782277:web:61fb163d3635936a3bcaac',
    messagingSenderId: '696348782277',
    projectId: 'hastane-acil-app',
    authDomain: 'hastane-acil-app.firebaseapp.com',
    storageBucket: 'hastane-acil-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB4L7YtiE8HJM8TPF7Ja1SgQe1teKygvA',
    appId: '1:696348782277:android:61fb163d3635936a3bcaac',
    messagingSenderId: '696348782277',
    projectId: 'hastane-acil-app',
    storageBucket: 'hastane-acil-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6bOTb86JkljpyfpNHwHCYyPhoe5l-goQ',
    appId: '1:696348782277:ios:61fb163d3635936a3bcaac',
    messagingSenderId: '696348782277',
    projectId: 'hastane-acil-app',
    storageBucket: 'hastane-acil-app.appspot.com',
    iosBundleId: 'com.example.hastane_acil_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6bOTb86JkljpyfpNHwHCYyPhoe5l-goQ',
    appId: '1:696348782277:macos:61fb163d3635936a3bcaac',
    messagingSenderId: '696348782277',
    projectId: 'hastane-acil-app',
    storageBucket: 'hastane-acil-app.appspot.com',
    iosBundleId: 'com.example.hastane_acil_app',
  );
}
